import type { VerificationReport } from "@/lib/types";

export const MOCK_REPORT: VerificationReport = {
  documentId: "doc_8f9321b0",
  documentType: "PASSPORT",
  issuingCountry: "USA",
  overallVerdict: "FLAGGED",
  compositeRiskScore: 87,
  processingTimeMs: 4280,
  capturedAt: "2026-09-05T14:32:11Z",
  submittedBy: "Security Officer // Desk 4",
  extractedFields: [
    {
      field: "Document Number",
      value: "XH3849201",
      expected: "XH3849201",
      confidence: 99.4,
      flagged: false,
    },
    {
      field: "First Name",
      value: "JOHN",
      expected: "JOHN",
      confidence: 99.1,
      flagged: false,
    },
    {
      field: "Last Name",
      value: "DOE",
      expected: "DOE",
      confidence: 98.5,
      flagged: false,
    },
    {
      field: "Date of Birth",
      value: "1988-04-12",
      expected: "1988-04-12",
      confidence: 64.2,
      flagged: true,
      reason: "Digital alteration detected in DOB region",
    },
    {
      field: "Expiration Date",
      value: "2028-05-11",
      expected: "2028-05-11",
      confidence: 71.8,
      flagged: true,
      reason: "Date pixel boundaries irregular vs. passport template",
    },
    {
      field: "Nationality",
      value: "USA",
      expected: "USA",
      confidence: 99.8,
      flagged: false,
    },
    {
      field: "Sex",
      value: "M",
      expected: "M",
      confidence: 99.9,
      flagged: false,
    },
    {
      field: "MRZ Text Line 2",
      value: "P<USADOE<<JOHN<XH3849201",
      expected: "P<USADOE<<JOHN<XH3849201",
      confidence: 82.3,
      flagged: true,
      reason: "Checksum digit mismatch on DOB field",
    },
  ],
  inspectionResults: {
    biometricMatch: {
      status: "PASSED",
      confidence: 98.4,
      livenessVerified: true,
      details: "Facial features matched against document photo. Liveness confirmed via micro-movement analysis.",
    },
    mrzCheck: {
      status: "FAILED",
      confidence: 31.6,
      checksumValid: false,
      details: "Line 2 checksum digit mismatch on DOB. Expected '19880412' checksum '6', found '9'.",
    },
    pixelForensics: {
      status: "FLAGGED",
      confidence: 76.5,
      boundingBoxes: [
        {
          x: 118,
          y: 82,
          width: 142,
          height: 52,
          label: "Font Inconsistency / Overlay",
          severity: "HIGH",
          confidence: 92.1,
          category: "Document Authenticity",
        },
        {
          x: 84,
          y: 160,
          width: 96,
          height: 44,
          label: "Photo Tampering Edge",
          severity: "HIGH",
          confidence: 88.7,
          category: "Photo Forensics",
        },
        {
          x: 380,
          y: 120,
          width: 120,
          height: 42,
          label: "DOB Region Alteration",
          severity: "HIGH",
          confidence: 84.3,
          category: "Data Integrity",
        },
        {
          x: 262,
          y: 210,
          width: 120,
          height: 36,
          label: "Hologram Sheen Anomaly",
          severity: "WARNING",
          confidence: 71.2,
          category: "Security Features",
        },
        {
          x: 40,
          y: 40,
          width: 180,
          height: 64,
          label: "MRZ Checksum Zone",
          severity: "WARNING",
          confidence: 69.8,
          category: "MRZ Verification",
        },
      ],
    },
    documentAuthenticity: {
      status: "FLAGGED",
      confidence: 74.2,
      details: "Three pixel-level alterations and one template mismatch detected.",
    },
    dataIntegrity: {
      status: "FAILED",
      confidence: 58.9,
      details: "MRZ checksum invalid; biometric DOB conflicts with MRZ DOB.",
    },
    faceMatch: {
      status: "PASSED",
      confidence: 96.7,
      livenessVerified: true,
    },
    hologramCheck: {
      status: "FLAGGED",
      confidence: 71.2,
      uvResponse: false,
      sheenVerified: true,
      details: "UV response weak in bottom-right region; sheen pattern otherwise consistent.",
    },
  },
};
